### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by jakob-keller** [Ponte-Energy-Partners/peprock#10]
- [x] add missing docstrings
- [x] expand `README.md`
- [x] generate and ship API documentation

**Comment by lorenzwalthert** [comment]
Fantastic Idea hehe 😄
We could start with a more informative `README.md` that will be nicely rendered on the landing page of the repo with a few examples on how to use the library.

**Comment by jakob-keller** [comment]
API Documentation now published to https://api.peprock.ponte.energy

**Comment by lorenzwalthert** [comment]
Great. Curious about your decision to use pdoc, which doc syntax etc. I might have a few additional ideas, in co junction with the documentation project we discussed some time ago.

**Comment by lorenzwalthert** [comment]
Also, I suggest to put the doc link at the repo page for easy access, that’s how most GitHub projects do it. So it will look like this (ie styler.r-lib.org). 
![C08F9EB9-DE61-44FF-BEA7-D494E93CB831](https://user-images.githubusercontent.com/10477073/222677647-f97183a4-6c17-4421-983c-3b9bca339e30.png)

**Comment by jakob-keller** [comment]
> Great. Curious about your decision to use pdoc, which doc syntax etc. I might have a few additional ideas, in co junction with the documentation project we discussed some time ago.

The decision to take `pdoc3` was due to its appeal as a zero-touch solution. I am open to change that anytime - there are also zero sunk costs at the moment.

**Comment by jakob-keller** [comment]
> Also, I suggest to put the doc link at the repo page for easy access, that’s how most GitHub projects do it. So it will look like this (ie styler.r-lib.org).

done

**Comment by lorenzwalthert** [comment]
👍

**Comment by lorenzwalthert** [comment]
It seems to be fairly easy to include the `README.md` in the rendered html: https://pdoc.dev/docs/pdoc.html#include-markdown-files.

**Comment by jakob-keller** [comment]
> It seems to be fairly easy to include the `README.md` in the rendered html: https://pdoc.dev/docs/pdoc.html#include-markdown-files.

We are using `pdoc3` for the API documentation. I don't think it has the same interface.

**Comment by lorenzwalthert** [comment]
You should not be allowed to use such similar names for such similar packages -.-
