### ISSUE TITLE
Move examples from `README.md` to docstring and test with doctest

### ISSUE THREAD

**Issue by lorenzwalthert** [Ponte-Energy-Partners/peprock#37]
* [doctest](https://docs.python.org/3/library/doctest.html) is an easy way to provide example code and output in a docstring and test if the output matches the expectations.
* this ensures up-to date examples with expected output.
* examples are most likely helpful close to the low-level docs. Previously, I argued examples are in the README, which I stand by still, but probably more to get a feel for what the modules are about, not to provide low-level information about how to use a callable.

**Comment by jakob-keller** [comment]
Fully agree with you, both in https://github.com/Ponte-Energy-Partners/peprock/issues/10#issuecomment-1445841499 as well as now.

**Comment by jakob-keller** [comment]
> * [doctest](https://docs.python.org/3/library/doctest.html) is an easy way to provide example code and output in a docstring and test if the output matches the expectations.

I gave it a try, but I can't get either pure `doctest` nor the `pytest` integration to work properly with our namespace packages. I believe that is currently unsupported.

**Comment by lorenzwalthert** [comment]
my quick research on the topic:

* [pytest only looks in `tests/`](https://stackoverflow.com/questions/17056138/how-to-make-pytest-run-doctests-as-well-as-normal-tests-director), we need package source.
* docopt has [troubles with relative imports](https://stackoverflow.com/questions/4047227/doctest-and-relative-imports) and absolute imports are generally recommended in [pep8](https://peps.python.org/pep-0008/) and the [google style guide](https://google.github.io/styleguide/pyguide.html#224-decision).

Apparently there are a lot of problems associated with relative imports in Python. I replaced your few relative imports with absolute and it worked (use `-v` for verbose output).

```
python -m doctest -v peprock/**/*.py
```
See my [doctest branch](https://github.com/lorenzwalthert/peprock/tree/doctest), which is a fork of yours.
