### ISSUE TITLE
Replace relative with absolute imports

### ISSUE THREAD

**Issue by jakob-keller** [Ponte-Energy-Partners/peprock#46]
* docopt has [troubles with relative imports](https://stackoverflow.com/questions/4047227/doctest-and-relative-imports) and absolute imports are generally recommended in [pep8](https://peps.python.org/pep-0008/) and the [google style guide](https://google.github.io/styleguide/pyguide.html#224-decision).

Apparently there are a lot of problems associated with relative imports in Python. I replaced your few relative imports with absolute and it worked (use `-v` for verbose output).

```
python -m doctest -v peprock/**/*.py
```
See my [doctest branch](https://github.com/lorenzwalthert/peprock/tree/doctest), which is a fork of yours.

_Originally posted by @lorenzwalthert in https://github.com/Ponte-Energy-Partners/peprock/issues/37#issuecomment-1460859133_

**Comment by jakob-keller** [comment]
@lorenzwalthert Could you put [your commit that makes all imports absolute](https://github.com/lorenzwalthert/peprock/commit/42016bacce93e5fda282b4a389d82cb6704a4531) into a separate PR? Thanks you!

**Comment by lorenzwalthert** [comment]
Realised that we don't need that anymore since you have changed the pytest settings (I believe `--import-mode=importlib` did the trick). I [reverted](https://github.com/lorenzwalthert/peprock/tree/doctest) 2699176fd5f66c6bb4eb5c0a84ea197edf8ff96e on the latest release and all checks green.

**Comment by lorenzwalthert** [comment]
If you want, we can revert to switch from relative to absolute imports.

**Comment by jakob-keller** [comment]
I might consider it, since I believe PEP8 allows relative imports in our case:

> However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose:
> 
> from . import sibling
> from .sibling import example
